# Generated by Django 5.2.3 on 2025-06-23 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_rename_posts_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
